-- ============================================
-- MIGRASI: Tambah kolom biodata lengkap
-- Jalankan di Supabase SQL Editor
-- ============================================

-- Hapus kolom lama yang sudah diganti
ALTER TABLE siswa DROP COLUMN IF EXISTS nama_ortu;

-- === DATA SISWA TAMBAHAN ===
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS nipd TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS nik TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS agama TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS rt TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS rw TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS dusun TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS kelurahan TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS kecamatan TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS kode_pos TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS jenis_tinggal TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS alat_transportasi TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS telepon TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS hp TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS email_siswa TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS skhun TEXT;

-- === DATA AYAH ===
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS ayah_nama TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS ayah_tahun_lahir TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS ayah_pendidikan TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS ayah_pekerjaan TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS ayah_penghasilan TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS ayah_nik TEXT;

-- === DATA IBU ===
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS ibu_nama TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS ibu_tahun_lahir TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS ibu_pendidikan TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS ibu_pekerjaan TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS ibu_penghasilan TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS ibu_nik TEXT;

-- === DATA WALI ===
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS wali_nama TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS wali_tahun_lahir TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS wali_pendidikan TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS wali_pekerjaan TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS wali_penghasilan TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS wali_nik TEXT;

-- === DATA BANTUAN & KIP ===
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS penerima_kip TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS nomor_kip TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS nama_di_kip TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS nomor_kks TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS no_reg_akta TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS bank TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS layak_pip TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS alasan_pip TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS kebutuhan_khusus TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS sekolah_asal TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS anak_ke INTEGER;

-- === DATA FISIK & LAIN ===
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS no_kk TEXT;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS berat_badan NUMERIC;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS tinggi_badan NUMERIC;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS lingkar_kepala NUMERIC;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS jml_saudara INTEGER;
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS jarak_rumah NUMERIC;
